### ISSUE TITLE
Example project generates Exception : 'Could not find a part of the path 'C:\logs\details.log'.'

### ISSUE THREAD

**Issue by bilalagha** [googleads/google-ads-dotnet#116]
When Debugging Example project generates below exception if there is no log folder in C drive. Should it not be creating a folder by default or ask to create a new log folder  as its an exe project. 

{System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\logs\details.log'.
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at Google.Ads.GoogleAds.Util.TraceUtilities.Configure(String source, String filePath, SourceLevels levels) in D:\data\GoogleAdsApi\google-ads-dotnet-master\google-ads-dotnet-master\src\Util\TraceUtilities.cs:line 119
   at Google.Ads.GoogleAds.Examples.Program.Main(String[] args) in D:\data\GoogleAdsApi\google-ads-dotnet-master\google-ads-dotnet-master\examples\Program.cs:line 37}

**Comment by AnashOommen** [comment]
It should be commented out. Do you want to send a pull request? Happy to review it.

**Comment by bilalagha** [comment]
> It should be commented out. Do you want to send a pull request? Happy to review it.
Sure Will do it.

**Comment by AnashOommen** [comment]
https://github.com/googleads/google-ads-dotnet/pull/144
