### ISSUE TITLE
Dependency Package CommandLineParser

### ISSUE THREAD

**Issue by akrock** [googleads/google-ads-dotnet#308]
**Which version of the client library are you using?** V 9.00 / 10.00

**Which version of .NET are you using?** .NET 5

**Which operating system (Linux, Windows, ...) and version?** Linux

**Expected result**
An API runtime package does not contain a package that is unused at runtime.

**Actual result**
The API runtime package contains the CommandLineParser.
 
**Anything else we should know about your project / environment**
This can be an issue for users who also have an implementation using CommandLineParser. In our case we were using `CommandLineParser` v2.3.0, which apparently is incompatible w/ the 2.8.0 version resulting in a runtime error.

While we were able to mitigate the issue this time, under different circumstances it might be more impactful. I would suggest that the code is refactored such that the runtime package does not have an added dependency that is only there to facilitate the examples.

```
2021-09-08T13:48:35.428991571Z Fatal Processing Error:
2021-09-08T13:48:35.429024672Z System.MissingMethodException: Method not found: 'Void CommandLine.VerbAttribute..ctor(System.String)'.
2021-09-08T13:48:35.429029672Z    at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
2021-09-08T13:48:35.429035372Z    at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
2021-09-08T13:48:35.429041772Z    at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctorWithParameters, Boolean& isVarArg)
2021-09-08T13:48:35.429051072Z    at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
2021-09-08T13:48:35.429054772Z    at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
2021-09-08T13:48:35.429061172Z    at System.RuntimeType.GetCustomAttributes(Type attributeType, Boolean inherit)
2021-09-08T13:48:35.429064273Z    at CommandLine.Core.Verb.<>c.<SelectFromTypes>b__14_0(Type type)
2021-09-08T13:48:35.429066973Z    at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
2021-09-08T13:48:35.429069973Z    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
2021-09-08T13:48:35.429072873Z    at System.Linq.Enumerable.WhereEnumerableIterator`1.GetCount(Boolean onlyIfCheap)
2021-09-08T13:48:35.429075773Z    at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
2021-09-08T13:48:35.429078573Z    at CommandLine.Core.InstanceChooser.Choose(Func`3 tokenizer, IEnumerable`1 types, IEnumerable`1 arguments, StringComparer nameComparer, Boolean ignoreValueCase, CultureInfo parsingCulture, Boolean autoHelp, Boolean autoVersion, IEnumerable`1 nonFatalErrors)
2021-09-08T13:48:35.429081973Z    at CommandLine.Parser.ParseArguments(IEnumerable`1 args, Type[] types)
```

**Comment by akrock** [comment]
@AnashOommen Changes that caused the issue were introduced with #286.
