### ISSUE TITLE
Upgrade from V10 to V13 Requires GRPC Which Fails on Arm64

### ISSUE THREAD

**Issue by coryshaw1** [googleads/google-ads-dotnet#501]
After updating to the latest Google.Ads.GoogleAds Nuget package, the Ads API is no longer functional on arm64 due to the Google.Ads.Gax > Grpc requirement. The grpc dll will not load with the error of "LoadLibrary failed with error 193".

```csharp
_client = new GoogleAdsClient(new GoogleAdsConfig
{
    OAuth2Mode = Google.Ads.Gax.Config.OAuth2Flow.APPLICATION,
    DeveloperToken = "***",
    OAuth2ClientId = "***.apps.googleusercontent.com",
    OAuth2ClientSecret = "***",
    OAuth2RefreshToken = "***",
    LoginCustomerId = "###" // manager account id
});
_service = _client.GetService(Google.Ads.GoogleAds.Services.V13.GoogleAdsService);
```

```
System.IO.IOException
  HResult=0x80131620
  Message=Error loading native library "Z:\cory\Dashboard\Dashboard\bin\grpc_csharp_ext.x64.dll". LoadLibrary failed with error 193
  Source=Grpc.Core
  StackTrace:
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethodsUsingExplicitLoad()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Google.Ads.Gax.Lib.AdsChannel.CreateGrpcCoreChannel(Uri uri, ChannelCredentials credentials)
   at Google.Ads.Gax.Lib.AdsChannel..ctor(AdsConfig config, String url)
   at Google.Ads.Gax.Lib.CachedChannelFactory.GetChannel(AdsConfig config, String serverUrl)
   at Google.Ads.GoogleAds.Lib.GoogleAdsServiceClientFactory.GetService[TService,TServiceSetting](ServiceTemplate`3 serviceTemplate, GoogleAdsConfig config)
   at Google.Ads.GoogleAds.Lib.GoogleAdsClient.GetService[TService,TServiceSetting](ServiceTemplate`3 serviceTemplate)
   at Dashboard.Core.GoogleAdWords.GoogleAdWordsService..ctor(Account account, IAccessRepository accessRepo) in Z:\cory\Dashboard\Dashboard.Core\GoogleAdWords\GoogleAdWordsService.cs:line 52
   at Microsoft.Practices.ObjectBuilder2.DynamicBuildPlanGenerationContext.<>c__DisplayClass1.<GetBuildMethod>b__0(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
```

**Comment by AnashOommen** [comment]
@coryshaw1 this isn't something I've changed at my end, so I've asked my colleagues in the grpc team to take a look at it.

**Comment by AnashOommen** [comment]
Just checking, does this work if you compile for AnyCpu? And this used to work for v10, right? What happens if you add a reference to Grpc.Core directly in your application and pin the version in your application to 2.41.0?

**Comment by AnashOommen** [comment]
On second thoughts: Did this even used to work for Windows? The ARM-specific support was available only for Linux IIRC.

**Comment by coryshaw1** [comment]
So I updated Google.Ads.GoogleAds Nuget package from 11.0.1.0 to 15.0.1.0 because of the v10 sunset. Everything was working well until the sunset of v10 of course when the API started erroring with the sunset notice.

I am on an ARM-based Mac running Windows 11 Arm64 in a VM due to legacy projects that are not updated to .NET core yet. The Solution and projects are all set to build for AnyCpu. I had a colleague test this same code on his Intel-based Mac running Windows 11 x64, and it worked fine for him without errors.

I attempted to build specifically for Arm64 with the same error. Have tried a complete reinstall of all packages, but still has errors.

New Package Installs from Update:
Google.Ads.Gax - 2.1.0

Various Package Updates that could be related:
Google.Ads.GoogleAds - 11.0.1.0 to 15.0.1.0
Google.Api.Gax.Grpc.GrpcCore - 3.5.0.0 to 3.7.0.0
Grpc.Core - 2.41.0 to 2.52.0

**Comment by coryshaw1** [comment]
Seems like that's giving me an object reference when instantiating the GoogleAdsClient:

```
Object reference not set to an instance of an object.
at Google.Ads.Gax.Util.ConfigUtilities.GetAppConfigPath()
at Google.Ads.Gax.Util.ConfigUtilities.GetSection(String sectionName)
at Google.Ads.Gax.Config.ConfigBase.ReadAppConfigSection(String sectionName)
at Google.Ads.Gax.Config.ConfigBase.LoadFromAppConfigSection(String sectionName)
at Google.Ads.GoogleAds.Config.GoogleAdsConfig..ctor()
at Dashboard.Core.GoogleAdWords.GoogleAdWordsService..ctor(Account account, IAccessRepository accessRepo) in Z:\\cory\\Dashboard\\Dashboard.Core\\GoogleAdWords\\GoogleAdWordsService.cs:line 42
```

**Comment by AnashOommen** [comment]
@coryshaw1 Try this attachment, I missed a place where I had to change a macro.

[Google.Ads.GoogleAds.Bundled.15.0.2.nupkg.zip](https://github.com/googleads/google-ads-dotnet/files/11117006/Google.Ads.GoogleAds.Bundled.15.0.2.nupkg.zip)

**Comment by coryshaw1** [comment]
Unfortunately still the same error, just a little bit of different stack trace:

```
System.IO.IOException
  HResult=0x80131620
  Message=Error loading native library "Z:\cory\Dashboard\Dashboard\bin\grpc_csharp_ext.x64.dll". LoadLibrary failed with error 193
  Source=Grpc.Core
  StackTrace:
at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
at Grpc.Core.Internal.NativeExtension.LoadNativeMethodsUsingExplicitLoad()
at Grpc.Core.Internal.NativeExtension..ctor()
at Grpc.Core.Internal.NativeExtension.Get()
at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
at Grpc.Core.GrpcEnvironment..ctor()
at Grpc.Core.GrpcEnvironment.AddRef()
at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
at Google.Ads.Gax.Lib.AdsChannel.CreateGrpcCoreChannel(Uri uri, ChannelCredentials credentials)
at Google.Ads.Gax.Lib.AdsChannel..ctor(AdsConfig config, String url)
at Google.Ads.Gax.Lib.CachedChannelFactory.GetChannel(AdsConfig config, String serverUrl)
at Google.Ads.GoogleAds.Lib.GoogleAdsServiceClientFactory.GetService[TService,TServiceSetting](ServiceTemplate`3 serviceTemplate, GoogleAdsConfig config)
at Google.Ads.GoogleAds.Lib.GoogleAdsClient.GetService[TService,TServiceSetting](ServiceTemplate`3 serviceTemplate)
at Dashboard.Core.GoogleAdWords.GoogleAdWordsService..ctor(Account account, IAccessRepository accessRepo) in Z:\\cory\\Dashboard\\Dashboard.Core\\GoogleAdWords\\GoogleAdWordsService.cs:line 52
at Microsoft.Practices.ObjectBuilder2.DynamicBuildPlanGenerationContext.<>c__DisplayClass1.<GetBuildMethod>b__0(IBuilderContext context)
at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
```

Now I did create a fresh solution from scratch, and only added Google.Ads.GoogleAds Nuget package (15.0.2). Did the same exact code from this issue where I just instantiated the GoogleAdsClient with the same credentials, and then attempted to retrieve the V13 service. Same VM/Windows arm64 setup, same .NET Framework version (4.7.2), and everything worked flawlessly. So grpc definitely is working on arm64 Windows. It just seems like maybe this specific solution is not fully understanding that this is running on Windows arm64 instead of x64? It is set to compile for Any CPU, and as I mentioned I've even tried to configure a build for arm64 only. It always fails with the same error regardless.

**Comment by AnashOommen** [comment]
I've seen .NET Framework csprojs get into weird states in the past -- a good example is the ASP.NET example I distribute as part of the SDK. I rebuild it from scratch once every 8-9 months because Visual Studio does something and I can't figure out what went wrong and how. Essentially what you did in this case.

Since it works with the solution from the scratch, it is probably simpler to just reconstruct the project?

**Comment by AnashOommen** [comment]
Closing this bug for now, since it seems that the original issue can be "fixed" if the csproj is fixed. The original Grpc.Core library has been sunset anyway, so there's little we can do to support this specific runtime if at all, officially.
