### ISSUE TITLE
Error:"invalid_request", Description:"Missing required parameter: refresh_token" using service_account credentials in .NET

### ISSUE THREAD

**Issue by TamaraGhazaryan** [googleads/google-ads-dotnet#535]
Hello,

Our company used **Google.Ads.GoogleAds** nuget package for google ads. It worked fine when we used version **14.2.0**. But recently we upgraded that package to use **17.0.0** version. After that we receive an errors each time when making a call.
I already contacted to google ads support team, they confirmed that they didn't introduce any changes and service account shouldn't have any refresh tokens and they navigated to here to resolve the issue. 

Here is the error:

```
Status(StatusCode="Internal", Detail="Error starting gRPC call. TokenResponseException: Error:"invalid_request", Description:"Missing required parameter: refresh_token", Uri:""", DebugException="Google.Apis.Auth.OAuth2.Responses.TokenResponseException: Error:"invalid_request", Description:"Missing required parameter: refresh_token", Uri:""
   at Google.Apis.Auth.OAuth2.Responses.TokenResponse.FromHttpResponseAsync(HttpResponseMessage response, IClock clock, ILogger logger)
   at Google.Apis.Auth.OAuth2.Requests.RequestExtensions.PostFormAsync(Object request, HttpClient httpClient, String url, AuthenticationHeaderValue authenticationHeaderValue, IClock clock, ILogger logger, CancellationToken taskCancellationToken)
   at Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.FetchTokenAsync(String userId, TokenRequest request, CancellationToken taskCancellationToken)
   at Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.FetchTokenAsync(String userId, TokenRequest request, CancellationToken taskCancellationToken)
   at Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.RefreshTokenAsync(String userId, String refreshToken, CancellationToken taskCancellationToken)
   at Google.Apis.Auth.OAuth2.UserCredential.RefreshTokenAsync(CancellationToken taskCancellationToken)
   at Google.Apis.Auth.OAuth2.TokenRefreshManager.RefreshTokenAsync()
   at Google.Apis.Auth.OAuth2.TokenRefreshManager.<GetAccessTokenForRequestAsync>g__LogException|10_0(Task task)
   at Google.Apis.Auth.OAuth2.TokenRefreshManager.GetAccessTokenForRequestAsync(CancellationToken cancellationToken)
   at Google.Apis.Auth.OAuth2.UserCredential.GetAccessTokenWithHeadersForRequestAsync(String authUri, CancellationToken cancellationToken)
   at Google.Apis.Auth.OAuth2.UserCredential.GetAccessTokenWithHeadersForRequestAsync(String authUri, CancellationToken cancellationToken)
   at Grpc.Auth.GoogleAuthInterceptors.<>c__DisplayClass3_0.<<FromCredential>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Grpc.Net.Client.Internal.GrpcProtocolHelpers.ReadCredentialMetadata(DefaultCallCredentialsConfigurator configurator, GrpcChannel channel, HttpRequestMessage message, IMethod method, CallCredentials credentials)
   at Grpc.Net.Client.Internal.GrpcCall`2.ReadCredentials(HttpRequestMessage request)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. TokenResponseException: Error:"invalid_request", Description:"Missing required parameter: refresh_token", Uri:""", DebugException="Google.Apis.Auth.OAuth2.Responses.TokenResponseException: Error:"invalid_request", Description:"Missing required parameter: refresh_token", Uri:""
   at Google.Apis.Auth.OAuth2.Responses.TokenResponse.FromHttpResponseAsync(HttpResponseMessage response, IClock clock, ILogger logger)
   at Google.Apis.Auth.OAuth2.Requests.RequestExtensions.PostFormAsync(Object request, HttpClient httpClient, String url, AuthenticationHeaderValue authenticationHeaderValue, IClock clock, ILogger logger, CancellationToken taskCancellationToken)
   at Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.FetchTokenAsync(String userId, TokenRequest request, CancellationToken taskCancellationToken)
   at Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.FetchTokenAsync(String userId, TokenRequest request, CancellationToken taskCancellationToken)
   at Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.RefreshTokenAsync(String userId, String refreshToken, CancellationToken taskCancellationToken)
   at Google.Apis.Auth.OAuth2.UserCredential.RefreshTokenAsync(CancellationToken taskCancellationToken)
   at Google.Apis.Auth.OAuth2.TokenRefreshManager.RefreshTokenAsync()
   at Google.Apis.Auth.OAuth2.TokenRefreshManager.<GetAccessTokenForRequestAsync>g__LogException|10_0(Task task)
   at Google.Apis.Auth.OAuth2.TokenRefreshManager.GetAccessTokenForRequestAsync(CancellationToken cancellationToken)
   at Google.Apis.Auth.OAuth2.UserCredential.GetAccessTokenWithHeadersForRequestAsync(String authUri, CancellationToken cancellationToken)
   at Google.Apis.Auth.OAuth2.UserCredential.GetAccessTokenWithHeadersForRequestAsync(String authUri, CancellationToken cancellationToken)
   at Grpc.Auth.GoogleAuthInterceptors.<>c__DisplayClass3_0.<<FromCredential>b__0>d.MoveNext()
```

And here is the code:

```
public class GoogleAdsClient : IGoogleAdsClient
{
    private readonly GoogleAdsConfig _config;
    private readonly GoogleAdsServiceClient _googleAdsServiceClient;

    public GoogleAdsClient(GoogleAdsConfig configuration)
    {
        _config = configuration;
        _googleAdsServiceClient = new Google.Ads.GoogleAds.Lib.GoogleAdsClient(_config).GetService(Services.V13.GoogleAdsService);
    }

    public async Task<List<GoogleAdsModel>> GetGoogleAdCampaigns(string fromDate, string toDate, string campaignIds, bool ignoreZipCodes = true)
    {
        var report = new List<GoogleAdsModel>();
        var query = new StringBuilder(@$"
                SELECT
                    campaign.id,
                    segments.date,
                    metrics.impressions,
                    metrics.clicks
                    {(ignoreZipCodes ? string.Empty : ", segments.geo_target_postal_code")}
               FROM user_location_view
               WHERE segments.date BETWEEN '{fromDate}' 
                    AND '{toDate}' 
                    AND campaign.id in ({campaignIds})");

        await _googleAdsServiceClient.SearchStreamAsync(_config.LoginCustomerId, query.ToString(),
               resp =>
               {
                   report.AddRange(resp.Results.Select(x => new GoogleAdsModel
                   {
                       CampaignId = x.Campaign.Id,
                       Date = x.Segments?.Date,
                       Hour = x.Segments?.Hour,
                       Impressions = x.Metrics?.Impressions,
                       Clicks = x.Metrics?.Clicks,
                       GeoTargetConstant = x.Segments?.GeoTargetPostalCode
                   }));
               }
           );

        return report;
    }
}
```

**Comment by Raibaz** [comment]
Hello, sorry to hear about your issue.

How are you populating the configuration properties in your `GoogleAdsConfig` object?

Please notice that we introduced a change in how the configuration properties are loaded in version 16.0.0 of the client library: you can refer to [this page](https://developers.google.com/google-ads/api/docs/client-libs/dotnet/configuration) for instructions on how to configure the credentials properly.

**Comment by TamaraGhazaryan** [comment]
Thank you for the information. The issue is fixed now.
