### ISSUE TITLE
can't upgrade past (now-obsolete) API V15

### ISSUE THREAD

**Issue by lgalbert** [googleads/google-ads-dotnet#575]
We were using V15 of the API and got a warning that it was about to be obsoleted, so attempted to upgrade our project to use V17 instead. Everything compiles OK, but we're getting runtime errors when we try to run a test to validate it's working. 

I tried building this library from source, and that didn't work; neither did upgrading the `Google.Api.Gax` package to `v4.9.0` that may be the cause. I'm not sure whether the error source is the `Google.Api.Gax package`, or the way that _this_ package interfaces with `Google.Api.Gax`.

So currently our previously-working code is queueing up requests as we're unable to upgrade our google ads plugin to our app, which isn't ideal as we've been forced into this situation of broken libraries!

.

Our simple test is just to run a search against the 'SearchStream` method of `GoogleAdsService` to retrieve all conversion_actions which have the UPLOAD_CLICKS type. 

This crashes out with the following stack trace:
```
Method not found: ‘System.Buffers.IBufferWRiter`1<Byte> Grpc.Core.serializationContext.GetBufferWriter()’. 
   at Google.Ads.GoogleAds.V17.Services.GoogleAdsService.__Helper_SerializeMessage(IMessage message, SerializationContext context)
   at Grpc.Core.Internal.AsyncCallBase`2.UnsafeSerialize(TWrite msg, DefaultSerializationContext context) in /var/local/git/grpc/src/csharp/Grpc.Core/Internal/AsyncCallBase.cs:line 257
   at Grpc.Core.Internal.AsyncCall`2.StartServerStreamingCall(TRequest msg) in /var/local/git/grpc/src/csharp/Grpc.Core/Internal/AsyncCall.cs:line 246
   at Grpc.Core.Calls.AsyncServerStreamingCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req) in /var/local/git/grpc/src/csharp/Grpc.Core/Calls.cs:line 84
   at Grpc.Core.DefaultCallInvoker.AsyncServerStreamingCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) in /var/local/git/grpc/src/csharp/Grpc.Core/DefaultCallInvoker.cs:line 66
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<AsyncServerStreamingCall>b__5_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx) in /_/src/Grpc.Core.Api/Interceptors/InterceptingCallInvoker.cs:line 75
   at Google.Ads.GoogleAds.Interceptors.GoogleAdsGrpcInterceptor.AsyncServerStreamingCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, AsyncServerStreamingCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.AsyncServerStreamingCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) in /_/src/Grpc.Core.Api/Interceptors/InterceptingCallInvoker.cs:line 72
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<AsyncServerStreamingCall>b__5_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx) in /_/src/Grpc.Core.Api/Interceptors/InterceptingCallInvoker.cs:line 75
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.AsyncServerStreamingCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, AsyncServerStreamingCallContinuation`2 continuation) in /_/src/Grpc.Core.Api/ClientBase.cs:line 215
   at Grpc.Core.Interceptors.InterceptingCallInvoker.AsyncServerStreamingCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) in /_/src/Grpc.Core.Api/Interceptors/InterceptingCallInvoker.cs:line 72
   at Google.Ads.GoogleAds.V17.Services.GoogleAdsService.GoogleAdsServiceClient.SearchStream(SearchGoogleAdsStreamRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiServerStreamingCall.<>c__DisplayClass0_0`2.<Create>b__1(TRequest req, CallSettings cs) in /_/Google.Api.Gax.Grpc/ApiServerStreamingCall.cs:line 26
   at Google.Ads.GoogleAds.V17.Services.GoogleAdsServiceClientImpl.SearchStream(SearchGoogleAdsStreamRequest request, CallSettings callSettings)
   at Google.Ads.GoogleAds.V17.Services.GoogleAdsServiceClient.SearchStreamAsync(SearchGoogleAdsStreamRequest request, Action`1 responseCallback, CallSettings callSettings)
   at Google.Ads.GoogleAds.V17.Services.GoogleAdsServiceClient.SearchStream(SearchGoogleAdsStreamRequest request, Action`1 responseCallback, CallSettings callSettings)
   at GoogleAdsPlugin.BusinessModels.GoogleAdsConfigurationRetrieveConversionActionsCommand.Execute(IList`1 context, IList`1 list, Selection`1 selection) in C:\Users\myuser\source\repos\myappPlugins\GoogleAdsPlugin\GoogleAdsPlugin\BusinessModels\GoogleAdsConfigurationRetrieveConversionActionsCommand.cs:line 74
```

**Steps to Reproduce:**
Code we're using is as below:
```
GoogleAdsClient client = new GoogleAdsClient(defaultConfig);

// Get the GoogleAdsService.
GoogleAdsServiceClient googleAdsService = client.GetService(Services.V17.GoogleAdsService);

// Create a query that will retrieve all UPLOAD_CLICKS conversion actions.
string query = @"SELECT
    conversion_action.id,
    conversion_action.resource_name,
    conversion_action.name,
    conversion_action.status
FROM conversion_action
WHERE conversion_action.type = 'UPLOAD_CLICKS'";

// Issue a search request.
googleAdsService.SearchStream(config.CustomerId, query,
    delegate (SearchGoogleAdsStreamResponse resp)
    {
        foreach (GoogleAdsRow googleAdsRow in resp.Results)
        {
            SimpleMessagePresenterFactory.ShowMessage("ConversionAction with ID {0} and name '{1}' was found.", googleAdsRow.ConversionAction?.Id, googleAdsRow.ConversionAction?.Name);
        }
    }
);
```

**Client library version and API version:**
Client library version: v21.0.0 of Google.Ads.GoogleAds (also v4.0.1 of Google.Ads.Gax and v1.68.0 of Google.Apis.Auth)
Google Ads API version: V17
.NET version: 4.8
Operating system: Windows

**Comment by Raibaz** [comment]
Looks like your application is using `Grpc.Core`, which is scheduled for sunset and no longer supported.

Did you by any chance explicitly set the `UseGrpcCore` flag to `true`?

Take a look at [this guide](https://developers.google.com/google-ads/api/docs/client-libs/dotnet/grpc-support) for information about the differences between `Grpc.Core` and `Grpc.Net.Client` and how to switch between the two: this should help.

**Comment by lgalbert** [comment]
No, we weren't setting `UseGrpcCore`, I've now explicitly it to false and still get the same error.

**Comment by lgalbert** [comment]
Unless it's the .NET version requirement that's wrong, this language on the linked guide is unclear as to whether .NET Framework 4.8 is supported: 

> The Google Ads API .NET library depends on the Google.Api.Gax.Grpc package (part of Google Cloud SDK). Due to the gRPC library change, this package has updated its .NET Framework major version to 4.0.0 and its runtime requirement to .NET Standard 2.1.

> As a result, the Google Ads API .NET library runtime requirement has been updated to .NET Standard 2.1. The Google Ads API library continues to support .NET Framework 4.7.2+ and .NET 5.0+.

**Comment by lgalbert** [comment]
According to this Microsoft resource, .NET Standard 2.1 isn't compatible with any .NET Framework version: [https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1)

**Comment by AnashOommen** [comment]
This sounds similar to https://github.com/grpc/grpc-dotnet/issues/1240. Perhaps a missing direct reference to System.Buffer or System.Memory might be the cause of this error. So the compiler might compile, but the assembly may not resolve at runtime.

I've attached a demo project that targets .NET Framework 4.8. See if you can unzip, substitute the necessary values in Program.cs, and run the application successfully? It works at my end, so if the demo works then you can compare the packages.config and the csproj files to see what might be missing / different.

About the .NET Standard part: The library compiles independently for `netstandard2.1;net472;net6.0;net8.0`. The library works for .NET 4.8 because it works for .NET 4.7.2. It is not dependent on .NET Standard 2.1 for working on .NET 4.8.

[TestNetFramework.zip](https://github.com/user-attachments/files/17346269/TestNetFramework.zip)

**Comment by lgalbert** [comment]
Thanks @AnashOommen that demo project worked, so I was able to rule out an issue with this package; after a bit of digging I discovered that the third-party app my plugin is for was loading another, incompatible, version of System.Memory so I updated the version the third-party app was using (copied the dll file to the app folder), and it now works.
